import type { CatalogKind } from '@opd/shared';

// The ready-made Doctor's Catalogue a clinic can add in one click ("Add
// common items"): the generics Indian OPDs prescribe most, in their usual
// strengths, each with well-known Indian brands; common lab tests and
// panels; and common imaging and diagnostic work. Adding it skips what's
// already there (and fills in missing brands on existing medicines); every
// entry can be edited or deleted, and brands added.
//
// Brands are examples of widely sold products for reference while
// prescribing, not an endorsement or an exhaustive market list.

export interface StarterItem {
  kind: CatalogKind;
  name: string;
  strength?: string;
  brands?: string[];
}

// [generic name, strength, brands...]
type Med = [string, string, ...string[]];

const MEDICINES: Med[] = [
  // ---- Analgesics, antipyretics, NSAIDs ----
  ['Paracetamol', '500 mg', 'Crocin', 'Calpol', 'Pacimol', 'Dolo 500'],
  ['Paracetamol', '650 mg', 'Dolo 650', 'Calpol 650', 'Crocin 650', 'P-650'],
  ['Paracetamol syrup', '250 mg/5 ml', 'Calpol 250', 'Crocin DS'],
  ['Paracetamol drops', '100 mg/ml', 'Calpol drops', 'P-125 drops'],
  ['Ibuprofen', '400 mg', 'Brufen 400', 'Ibugesic 400'],
  ['Ibuprofen + Paracetamol', '400/325 mg', 'Combiflam', 'Ibugesic Plus'],
  ['Ibuprofen + Paracetamol suspension', '100/162.5 mg/5 ml', 'Ibugesic Plus suspension', 'Combiflam suspension'],
  ['Diclofenac', '50 mg', 'Voveran 50', 'Dynapar'],
  ['Diclofenac SR', '100 mg', 'Voveran SR 100', 'Dynapar SR'],
  ['Diclofenac + Paracetamol', '50/325 mg', 'Dicloran', 'Voveran Plus'],
  ['Diclofenac gel', '1%', 'Volini', 'Voveran Emulgel'],
  ['Aceclofenac', '100 mg', 'Hifenac', 'Zerodol'],
  ['Aceclofenac + Paracetamol', '100/325 mg', 'Zerodol-P', 'Hifenac-P', 'Aceclo Plus'],
  ['Aceclofenac + Paracetamol + Serratiopeptidase', '100/325/15 mg', 'Zerodol-SP', 'Hifenac-SP'],
  ['Mefenamic acid', '500 mg', 'Meftal 500', 'Ponstan'],
  ['Mefenamic acid + Dicyclomine', '250/10 mg', 'Meftal-Spas'],
  ['Mefenamic acid suspension', '100 mg/5 ml', 'Meftal-P'],
  ['Naproxen', '500 mg', 'Naprosyn', 'Napra'],
  ['Etoricoxib', '90 mg', 'Etoshine', 'Nucoxia', 'Arcoxia'],
  ['Etoricoxib', '120 mg', 'Etoshine 120', 'Nucoxia 120'],
  ['Nimesulide', '100 mg', 'Nise', 'Nimulid'],
  ['Piroxicam', '20 mg', 'Dolonex', 'Pirox'],
  ['Tramadol', '50 mg', 'Contramal', 'Tramazac'],
  ['Tramadol + Paracetamol', '37.5/325 mg', 'Ultracet', 'Tramazac-P'],
  ['Ketorolac', '10 mg', 'Ketorol', 'Toradol'],
  ['Aspirin', '75 mg', 'Ecosprin 75', 'Loprin 75'],
  ['Aspirin', '150 mg', 'Ecosprin 150'],
  ['Thiocolchicoside', '4 mg', 'Myoril', 'Thiospas'],
  ['Thiocolchicoside + Aceclofenac', '4/100 mg', 'Zerodol-TH', 'Hifenac-MR'],
  ['Chlorzoxazone + Paracetamol', '250/300 mg', 'Parafon DSC'],
  ['Serratiopeptidase', '10 mg', 'Serratiflam', 'Emanzen'],
  ['Colchicine', '0.5 mg', 'Zycolchin'],
  ['Febuxostat', '40 mg', 'Febutaz', 'Zurig'],
  ['Allopurinol', '100 mg', 'Zyloric', 'Ciploric'],

  // ---- Antibiotics ----
  ['Amoxicillin', '250 mg', 'Mox 250', 'Novamox 250'],
  ['Amoxicillin', '500 mg', 'Mox 500', 'Novamox 500', 'Amoxil'],
  ['Amoxicillin + Clavulanic acid', '625 mg', 'Augmentin 625', 'Clavam 625', 'Moxclav 625'],
  ['Amoxicillin + Clavulanic acid', '375 mg', 'Augmentin 375', 'Clavam 375'],
  ['Amoxicillin + Clavulanic acid suspension', '228.5 mg/5 ml', 'Augmentin Duo', 'Clavam DS', 'Moxclav DS'],
  ['Ampicillin + Cloxacillin', '500 mg', 'Megapen', 'Ampilox'],
  ['Azithromycin', '250 mg', 'Azithral 250', 'Azee 250'],
  ['Azithromycin', '500 mg', 'Azithral 500', 'Azee 500', 'Zithromax'],
  ['Azithromycin suspension', '200 mg/5 ml', 'Azithral XL', 'Azee Rediuse'],
  ['Clarithromycin', '500 mg', 'Claribid', 'Crixan'],
  ['Erythromycin', '500 mg', 'Althrocin', 'Erythrocin'],
  ['Cefixime', '200 mg', 'Taxim-O 200', 'Zifi 200', 'Cefix'],
  ['Cefixime suspension', '100 mg/5 ml', 'Taxim-O DS', 'Zifi DS'],
  ['Cefpodoxime', '200 mg', 'Cepodem', 'Monocef-O'],
  ['Cefuroxime', '500 mg', 'Ceftum', 'Zinacef'],
  ['Cefadroxil', '500 mg', 'Droxyl', 'Cefadrox'],
  ['Cephalexin', '500 mg', 'Sporidex', 'Phexin'],
  ['Cefdinir', '300 mg', 'Adcef', 'Cednir'],
  ['Ceftriaxone injection', '1 g', 'Monocef', 'Ceftriax', 'Oframax'],
  ['Ciprofloxacin', '500 mg', 'Ciplox 500', 'Cifran'],
  ['Levofloxacin', '500 mg', 'Levoflox 500', 'Glevo 500', 'Tavanic'],
  ['Levofloxacin', '750 mg', 'Levoflox 750', 'Glevo 750'],
  ['Ofloxacin', '200 mg', 'Zanocin 200', 'Oflox 200'],
  ['Ofloxacin + Ornidazole', '200/500 mg', 'Zanocin-OZ', 'O2', 'Oflox-OZ'],
  ['Norfloxacin', '400 mg', 'Norflox 400'],
  ['Norfloxacin + Tinidazole', '400/600 mg', 'Norflox-TZ', 'Tiniba-N'],
  ['Moxifloxacin', '400 mg', 'Moxif', 'Avelox'],
  ['Doxycycline', '100 mg', 'Doxy-1 L-DR Forte', 'Doxt-SL', 'Microdox'],
  ['Minocycline', '50 mg', 'Minoz', 'Cynomycin'],
  ['Linezolid', '600 mg', 'Linospan', 'Lizolid'],
  ['Nitrofurantoin', '100 mg', 'Niftran', 'Martifur'],
  ['Cotrimoxazole', '800/160 mg', 'Septran DS', 'Bactrim DS'],
  ['Metronidazole', '400 mg', 'Flagyl 400', 'Metrogyl 400'],
  ['Metronidazole suspension', '200 mg/5 ml', 'Metrogyl suspension', 'Flagyl suspension'],
  ['Tinidazole', '500 mg', 'Tiniba', 'Fasigyn'],
  ['Ornidazole', '500 mg', 'Dazolic', 'Giro'],
  ['Secnidazole', '1 g', 'Secnil', 'Noscote'],
  ['Rifaximin', '400 mg', 'Rifagut', 'Xifaxan'],
  ['Fosfomycin sachet', '3 g', 'Fosirol', 'Urifos'],
  ['Clindamycin', '300 mg', 'Dalacin C', 'Clincin'],
  ['Mupirocin ointment', '2%', 'T-Bact', 'Bactroban'],
  ['Fusidic acid cream', '2%', 'Fucidin', 'Fusiderm'],
  ['Silver sulfadiazine cream', '1%', 'Silverex', 'Burnheal'],

  // ---- Antifungals, antivirals, antiparasitics ----
  ['Fluconazole', '150 mg', 'Forcan 150', 'Zocon 150'],
  ['Itraconazole', '100 mg', 'Canditral', 'Itaspor'],
  ['Itraconazole', '200 mg', 'Itaspor 200', 'Canditral 200'],
  ['Terbinafine', '250 mg', 'Terbicip', 'Lamisil'],
  ['Clotrimazole cream', '1%', 'Candid', 'Canesten'],
  ['Clotrimazole vaginal tablet', '100 mg', 'Candid-V6', 'Candid-V3'],
  ['Clotrimazole mouth paint', '1%', 'Candid mouth paint'],
  ['Ketoconazole cream', '2%', 'Nizral cream', 'Ketoz'],
  ['Ketoconazole shampoo', '2%', 'Nizral shampoo', 'Ketoz shampoo'],
  ['Luliconazole cream', '1%', 'Lulifin', 'Lulican'],
  ['Miconazole cream', '2%', 'Daktarin', 'Zole'],
  ['Nystatin suspension', '100000 IU/ml', 'Mycostatin'],
  ['Acyclovir', '400 mg', 'Zovirax 400', 'Acivir 400'],
  ['Acyclovir', '800 mg', 'Acivir 800', 'Zovirax 800'],
  ['Acyclovir cream', '5%', 'Zovirax cream', 'Acivir cream'],
  ['Valacyclovir', '1 g', 'Valcivir', 'Valtrex'],
  ['Oseltamivir', '75 mg', 'Fluvir', 'Tamiflu'],
  ['Albendazole', '400 mg', 'Zentel', 'Albenda'],
  ['Albendazole suspension', '200 mg/5 ml', 'Zentel suspension'],
  ['Mebendazole', '100 mg', 'Mebex', 'Wormin'],
  ['Ivermectin', '12 mg', 'Ivecop 12', 'Scabo 12'],
  ['Permethrin cream', '5%', 'Permite', 'Scaboma'],
  ['Nitazoxanide', '500 mg', 'Nizonide', 'Netazox'],
  ['Hydroxychloroquine', '200 mg', 'HCQS', 'Plaquenil'],
  ['Artemether + Lumefantrine', '80/480 mg', 'Lumerax', 'Coartem'],
  ['Chloroquine', '250 mg', 'Lariago', 'Resochin'],

  // ---- Gastrointestinal ----
  ['Pantoprazole', '40 mg', 'Pan 40', 'Pantocid 40', 'Pantop 40'],
  ['Pantoprazole + Domperidone', '40/30 mg', 'Pan-D', 'Pantocid-DSR', 'Pantop-D'],
  ['Omeprazole', '20 mg', 'Omez', 'Ocid'],
  ['Omeprazole + Domperidone', '20/10 mg', 'Omez-D'],
  ['Rabeprazole', '20 mg', 'Razo 20', 'Rablet 20', 'Rabicip'],
  ['Rabeprazole + Domperidone', '20/30 mg', 'Razo-D', 'Rablet-D', 'Rabicip-DSR'],
  ['Esomeprazole', '40 mg', 'Nexpro 40', 'Sompraz 40'],
  ['Esomeprazole + Domperidone', '40/30 mg', 'Nexpro RD', 'Sompraz-D'],
  ['Lansoprazole', '30 mg', 'Lanzol', 'Lan'],
  ['Famotidine', '40 mg', 'Famocid 40', 'Topcid'],
  ['Ranitidine', '150 mg', 'Zinetac', 'Rantac 150'],
  ['Domperidone', '10 mg', 'Domstal', 'Vomistop'],
  ['Domperidone suspension', '5 mg/5 ml', 'Domstal suspension'],
  ['Ondansetron', '4 mg', 'Emeset 4', 'Vomikind 4', 'Ondem'],
  ['Ondansetron MD', '8 mg', 'Emeset 8', 'Vomikind 8'],
  ['Ondansetron syrup', '2 mg/5 ml', 'Emeset syrup', 'Vomikind syrup'],
  ['Metoclopramide', '10 mg', 'Perinorm', 'Reglan'],
  ['Levosulpiride', '25 mg', 'Levazeo', 'Sulpitac'],
  ['Itopride', '50 mg', 'Ganaton', 'Itoflux'],
  ['Antacid gel', '10 ml', 'Digene', 'Gelusil MPS', 'Mucaine'],
  ['Sucralfate suspension', '1 g/10 ml', 'Sucrafil', 'Sucral'],
  ['Sodium alginate + Antacid suspension', '10 ml', 'Gaviscon', 'Rantac Liquid'],
  ['Dicyclomine', '20 mg', 'Cyclopam', 'Bentyl'],
  ['Dicyclomine + Paracetamol', '20/500 mg', 'Cyclopam', 'Spasmonil Plus'],
  ['Drotaverine', '80 mg', 'Drotin', 'Doverin'],
  ['Drotaverine + Mefenamic acid', '80/250 mg', 'Drotin-M', 'Doverin-M'],
  ['Hyoscine butylbromide', '10 mg', 'Buscopan'],
  ['Mebeverine', '135 mg', 'Colospa', 'Mebaspa'],
  ['Loperamide', '2 mg', 'Imodium', 'Eldoper'],
  ['Racecadotril', '100 mg', 'Redotil', 'Racigyl'],
  ['Oral rehydration salts', '21 g sachet', 'Electral', 'ORS-L', 'Enerzal'],
  ['Zinc', '20 mg', 'Zinconia', 'Z&D'],
  ['Probiotic sachet', '1 sachet', 'Econorm', 'Enterogermina', 'Vibact'],
  ['Probiotic capsule', '1 cap', 'Bifilac', 'Vibact', 'Darolac'],
  ['Lactulose solution', '10 g/15 ml', 'Duphalac', 'Looz'],
  ['Bisacodyl', '5 mg', 'Dulcolax', 'Bisacodyl'],
  ['Sodium picosulfate', '10 mg', 'Cremalax', 'Laxopeg'],
  ['Liquid paraffin + Milk of magnesia', '15 ml', 'Cremaffin', 'Cremaffin Plus'],
  ['Isabgol husk', '3.5 g', 'Sat Isabgol', 'Naturolax'],
  ['Polyethylene glycol sachet', '17 g', 'Peglec', 'Softovac'],
  ['Ursodeoxycholic acid', '300 mg', 'Udiliv 300', 'Ursocol 300'],
  ['Simethicone drops', '40 mg/ml', 'Colicaid'],
  ['Pancreatin', '150 mg', 'Creon 10000', 'Panlipase'],
  ['Lignocaine + Hydrocortisone ointment', '3%/0.25%', 'Proctosedyl', 'Anovate'],

  // ---- Respiratory, allergy, cough & cold ----
  ['Cetirizine', '10 mg', 'Cetzine', 'Okacet', 'Alerid'],
  ['Levocetirizine', '5 mg', 'Levocet', 'Xyzal', 'Teczine'],
  ['Levocetirizine + Montelukast', '5/10 mg', 'Montair-LC', 'Montek-LC', 'Telekast-L'],
  ['Montelukast', '10 mg', 'Montair 10', 'Romilast', 'Singulair'],
  ['Montelukast + Levocetirizine syrup', '4/2.5 mg/5 ml', 'Montair-LC Kid', 'Montek-LC syrup'],
  ['Fexofenadine', '120 mg', 'Allegra 120', 'Fexova'],
  ['Fexofenadine', '180 mg', 'Allegra 180', 'Fexova 180'],
  ['Bilastine', '20 mg', 'Bilaxten', 'Bilasure'],
  ['Desloratadine', '5 mg', 'Deslor', 'Neoclarityn'],
  ['Hydroxyzine', '25 mg', 'Atarax', 'Hizine'],
  ['Chlorpheniramine + Phenylephrine + Paracetamol', '2/10/325 mg', 'Sinarest', 'Coldact', 'Cheston Cold'],
  ['Cetirizine + Phenylephrine + Paracetamol', '5/10/325 mg', 'Okacet Cold', 'Cheston Cold'],
  ['Dextromethorphan syrup', '10 mg/5 ml', 'Benadryl DR', 'Alex', 'Grilinctus'],
  ['Ambroxol + Guaifenesin + Terbutaline syrup', '100 ml', 'Ascoril', 'Ascoril LS'],
  ['Levosalbutamol + Ambroxol + Guaifenesin syrup', '100 ml', 'Ascoril LS', 'Asthalin Expectorant'],
  ['Codeine + Chlorpheniramine syrup', '10 mg/4 mg/5 ml', 'Corex', 'Phensedyl'],
  ['Ambroxol', '30 mg', 'Mucolite', 'Ambrodil'],
  ['Acetylcysteine', '600 mg', 'Mucinac', 'Fluimucil'],
  ['Salbutamol', '4 mg', 'Asthalin 4'],
  ['Salbutamol inhaler', '100 mcg', 'Asthalin inhaler', 'Ventolin'],
  ['Levosalbutamol inhaler', '50 mcg', 'Levolin inhaler'],
  ['Levosalbutamol respules', '0.63 mg', 'Levolin respules'],
  ['Budesonide respules', '0.5 mg', 'Budecort respules', 'Pulmicort'],
  ['Budesonide + Formoterol inhaler', '200/6 mcg', 'Foracort 200', 'Budamate 200', 'Symbicort'],
  ['Fluticasone + Salmeterol inhaler', '250/25 mcg', 'Seroflo 250', 'Esiflo 250'],
  ['Tiotropium inhaler', '9 mcg', 'Tiova', 'Spiriva'],
  ['Ipratropium + Levosalbutamol respules', '500/1.25 mcg', 'Duolin respules'],
  ['Doxofylline', '400 mg', 'Doxobid', 'Doxolin'],
  ['Theophylline + Etofylline', '23/77 mg', 'Deriphyllin'],
  ['Fluticasone nasal spray', '50 mcg', 'Flomist', 'Fluticone'],
  ['Mometasone nasal spray', '50 mcg', 'Metaspray', 'Nasonex'],
  ['Oxymetazoline nasal spray', '0.05%', 'Otrivin Oxy', 'Nasivion'],
  ['Xylometazoline nasal drops', '0.1%', 'Otrivin', 'Xylomist'],
  ['Saline nasal drops', '0.65%', 'Nasoclear', 'Solspre'],

  // ---- Cardiovascular ----
  ['Amlodipine', '5 mg', 'Amlong 5', 'Stamlo 5', 'Amlopress 5'],
  ['Amlodipine', '10 mg', 'Amlong 10', 'Stamlo 10'],
  ['Telmisartan', '40 mg', 'Telma 40', 'Telsar 40', 'Telvas 40'],
  ['Telmisartan', '80 mg', 'Telma 80', 'Telsar 80'],
  ['Telmisartan + Amlodipine', '40/5 mg', 'Telma-AM', 'Telsar-A', 'Telvas-AM'],
  ['Telmisartan + Hydrochlorothiazide', '40/12.5 mg', 'Telma-H', 'Telsar-H'],
  ['Losartan', '50 mg', 'Losar 50', 'Repace 50', 'Covance'],
  ['Losartan + Hydrochlorothiazide', '50/12.5 mg', 'Losar-H', 'Repace-H'],
  ['Olmesartan', '20 mg', 'Olmezest 20', 'Olmy 20', 'Benitec'],
  ['Olmesartan', '40 mg', 'Olmezest 40', 'Olmy 40'],
  ['Valsartan', '80 mg', 'Valent', 'Diovan'],
  ['Enalapril', '5 mg', 'Envas 5', 'Enam 5'],
  ['Ramipril', '5 mg', 'Cardace 5', 'Ramistar'],
  ['Cilnidipine', '10 mg', 'Cilacar', 'Cinod'],
  ['Nifedipine retard', '20 mg', 'Depin retard', 'Calcigard retard'],
  ['Metoprolol succinate', '25 mg', 'Met XL 25', 'Metolar XR 25', 'Revelol XL 25'],
  ['Metoprolol succinate', '50 mg', 'Met XL 50', 'Metolar XR 50'],
  ['Atenolol', '50 mg', 'Aten 50', 'Tenormin'],
  ['Bisoprolol', '5 mg', 'Concor 5', 'Bisoheart'],
  ['Nebivolol', '5 mg', 'Nebicard 5', 'Nodon'],
  ['Carvedilol', '6.25 mg', 'Carca 6.25', 'Cardivas 6.25'],
  ['Propranolol', '40 mg', 'Ciplar 40', 'Inderal'],
  ['Hydrochlorothiazide', '12.5 mg', 'Aquazide 12.5', 'Hydrazide'],
  ['Chlorthalidone', '12.5 mg', 'Thalizide', 'Clorthal'],
  ['Furosemide', '40 mg', 'Lasix', 'Frusemide'],
  ['Torsemide', '10 mg', 'Dytor 10', 'Tide 10'],
  ['Spironolactone', '25 mg', 'Aldactone', 'Spiractin'],
  ['Atorvastatin', '10 mg', 'Atorva 10', 'Lipvas 10', 'Storvas 10'],
  ['Atorvastatin', '20 mg', 'Atorva 20', 'Lipvas 20', 'Storvas 20'],
  ['Atorvastatin', '40 mg', 'Atorva 40', 'Lipvas 40'],
  ['Rosuvastatin', '10 mg', 'Rosuvas 10', 'Rozavel 10', 'Crestor'],
  ['Rosuvastatin', '20 mg', 'Rosuvas 20', 'Rozavel 20'],
  ['Fenofibrate', '160 mg', 'Lipicard 160', 'Fenolip'],
  ['Clopidogrel', '75 mg', 'Clopilet 75', 'Deplatt 75', 'Plavix'],
  ['Aspirin + Clopidogrel', '75/75 mg', 'Ecosprin-AV', 'Deplatt-A 75', 'Clopitab-A'],
  ['Aspirin + Atorvastatin', '75/10 mg', 'Ecosprin AV 75', 'Atorva-Asp'],
  ['Isosorbide mononitrate', '30 mg', 'Monotrate OD', 'Imdur'],
  ['Nitroglycerin sublingual', '0.5 mg', 'Angised', 'Nitrocin'],
  ['Trimetazidine MR', '35 mg', 'Flavedon MR', 'Trivedon MR'],
  ['Ivabradine', '5 mg', 'Ivabrad', 'Coraxan'],
  ['Digoxin', '0.25 mg', 'Lanoxin', 'Digox'],
  ['Warfarin', '5 mg', 'Warf 5', 'Coumadin'],
  ['Apixaban', '5 mg', 'Eliquis', 'Apigat'],

  // ---- Diabetes ----
  ['Metformin', '500 mg', 'Glycomet 500', 'Glyciphage 500', 'Obimet 500'],
  ['Metformin SR', '1000 mg', 'Glycomet SR 1000', 'Glyciphage SR 1 g'],
  ['Glimepiride', '1 mg', 'Amaryl 1', 'Glimisave 1', 'Zoryl 1'],
  ['Glimepiride', '2 mg', 'Amaryl 2', 'Glimisave 2', 'Zoryl 2'],
  ['Glimepiride + Metformin', '1/500 mg', 'Glycomet-GP 1', 'Amaryl M 1', 'Gemer 1'],
  ['Glimepiride + Metformin', '2/500 mg', 'Glycomet-GP 2', 'Amaryl M 2', 'Gemer 2'],
  ['Gliclazide MR', '60 mg', 'Glizid MR 60', 'Diamicron MR'],
  ['Gliclazide + Metformin', '80/500 mg', 'Glizid-M', 'Reclide-M'],
  ['Sitagliptin', '100 mg', 'Januvia', 'Istavel', 'Zita'],
  ['Sitagliptin + Metformin', '50/500 mg', 'Janumet 50/500', 'Istamet 50/500'],
  ['Vildagliptin', '50 mg', 'Galvus', 'Jalra', 'Zomelis'],
  ['Vildagliptin + Metformin', '50/500 mg', 'Galvus Met 50/500', 'Jalra-M 50/500'],
  ['Teneligliptin', '20 mg', 'Tenepride', 'Teneza', 'Zita Plus'],
  ['Linagliptin', '5 mg', 'Trajenta', 'Ondero'],
  ['Dapagliflozin', '10 mg', 'Forxiga', 'Dapanorm', 'Oxra'],
  ['Empagliflozin', '10 mg', 'Jardiance', 'Gibtulio'],
  ['Pioglitazone', '15 mg', 'Pioz 15', 'Piosys'],
  ['Voglibose', '0.3 mg', 'Volibo', 'Voglitor'],
  ['Insulin glargine', '100 IU/ml', 'Lantus', 'Basalog', 'Glaritus'],
  ['Insulin human premix 30/70', '40 IU/ml', 'Huminsulin 30/70', 'Mixtard 30/70'],
  ['Insulin aspart', '100 IU/ml', 'NovoRapid'],

  // ---- Thyroid, endocrine, steroids ----
  ['Levothyroxine', '25 mcg', 'Thyronorm 25', 'Eltroxin 25', 'Thyrox 25'],
  ['Levothyroxine', '50 mcg', 'Thyronorm 50', 'Eltroxin 50', 'Thyrox 50'],
  ['Levothyroxine', '75 mcg', 'Thyronorm 75', 'Thyrox 75'],
  ['Levothyroxine', '100 mcg', 'Thyronorm 100', 'Eltroxin 100', 'Thyrox 100'],
  ['Carbimazole', '5 mg', 'Neo-Mercazole', 'Thyrocab'],
  ['Prednisolone', '5 mg', 'Wysolone 5', 'Omnacortil 5'],
  ['Prednisolone', '10 mg', 'Wysolone 10', 'Omnacortil 10'],
  ['Prednisolone', '20 mg', 'Wysolone 20', 'Omnacortil 20'],
  ['Methylprednisolone', '8 mg', 'Medrol 8', 'Depopred'],
  ['Deflazacort', '6 mg', 'Defcort 6', 'Moaid'],
  ['Dexamethasone', '0.5 mg', 'Decdan', 'Dexona'],
  ['Hydrocortisone', '10 mg', 'Wycort', 'Lycortin'],

  // ---- Vitamins, minerals, supplements ----
  ['Vitamin D3 (Cholecalciferol)', '60000 IU', 'Uprise-D3', 'Calcirol', 'D-Rise', 'Tayo 60K'],
  ['Calcium + Vitamin D3', '500 mg/250 IU', 'Shelcal 500', 'Calcimax 500', 'CCM'],
  ['Calcium citrate + Vitamin D3', '1000 mg/400 IU', 'Shelcal-HD', 'Cipcal-HD'],
  ['Iron + Folic acid', '100 mg/1.5 mg', 'Livogen', 'Orofer XT', 'Autrin'],
  ['Ferrous ascorbate + Folic acid', '100 mg/1.5 mg', 'Orofer XT', 'Livogen XT'],
  ['Iron sucrose injection', '100 mg', 'Orofer-S', 'Venofer'],
  ['Ferric carboxymaltose injection', '500 mg', 'Encicarb', 'Ferinject'],
  ['Folic acid', '5 mg', 'Folvite', 'Fol-5'],
  ['Methylcobalamin', '1500 mcg', 'Mecobalamin', 'Nurokind', 'Methycobal'],
  ['Methylcobalamin + Pregabalin', '750 mcg/75 mg', 'Pregeb-M 75', 'Pregalin-M 75', 'Nurokind-G'],
  ['Vitamin B complex', '1 cap', 'Becosules', 'Neurobion Forte', 'Supradyn'],
  ['Multivitamin + Multimineral', '1 tab', 'Supradyn', 'Revital H', 'A to Z NS', 'Zincovit'],
  ['Vitamin C', '500 mg', 'Celin 500', 'Limcee'],
  ['Vitamin E', '400 mg', 'Evion 400'],
  ['Zinc + Multivitamin syrup', '200 ml', 'Zincovit syrup', 'A to Z syrup'],
  ['Protein powder', '200 g', 'Protinex', 'Proteinules', 'Ensure'],
  ['Omega-3 fatty acids', '1000 mg', 'Maxepa', 'Seacod'],
  ['Potassium chloride syrup', '15 ml', 'K-Cit', 'Potklor'],
  ['Sodium bicarbonate', '500 mg', 'Sodamint'],

  // ---- Neurology, psychiatry ----
  ['Pregabalin', '75 mg', 'Lyrica', 'Pregeb 75', 'Pregalin 75'],
  ['Gabapentin', '300 mg', 'Gabapin 300', 'Gabantin 300'],
  ['Amitriptyline', '10 mg', 'Tryptomer 10', 'Amitone 10'],
  ['Nortriptyline + Pregabalin', '10/75 mg', 'Nuroday-NT', 'Pregeb-NT'],
  ['Escitalopram', '10 mg', 'Nexito 10', 'S Citadep 10', 'Cipralex'],
  ['Sertraline', '50 mg', 'Serta 50', 'Daxid 50', 'Zoloft'],
  ['Fluoxetine', '20 mg', 'Fludac 20', 'Prodep 20'],
  ['Clonazepam', '0.5 mg', 'Clonotril 0.5', 'Rivotril 0.5', 'Lonazep 0.5'],
  ['Alprazolam', '0.25 mg', 'Alprax 0.25', 'Restyl 0.25'],
  ['Etizolam', '0.5 mg', 'Etilaam 0.5', 'Etizola'],
  ['Zolpidem', '10 mg', 'Zolfresh 10', 'Nitrest 10'],
  ['Propranolol + Flunarizine', '40/10 mg', 'Sibelium Plus', 'Flunarin Plus'],
  ['Flunarizine', '10 mg', 'Sibelium 10', 'Flunarin 10'],
  ['Betahistine', '16 mg', 'Vertin 16', 'Betavert 16'],
  ['Cinnarizine + Dimenhydrinate', '20/40 mg', 'Stugeron Forte', 'Vertigon'],
  ['Prochlorperazine', '5 mg', 'Stemetil', 'Vomitex'],
  ['Sumatriptan', '50 mg', 'Suminat 50', 'Imitrex'],
  ['Naproxen + Domperidone', '500/10 mg', 'Naprosyn Plus', 'Naxdom'],
  ['Levetiracetam', '500 mg', 'Levipil 500', 'Levroxa 500', 'Keppra'],
  ['Sodium valproate CR', '500 mg', 'Valparin Chrono 500', 'Encorate Chrono 500'],
  ['Phenytoin', '100 mg', 'Eptoin 100', 'Dilantin'],
  ['Carbamazepine', '200 mg', 'Tegretol 200', 'Mazetol 200'],
  ['Donepezil', '5 mg', 'Donep 5', 'Aricep'],
  ['Citicoline', '500 mg', 'Strocit', 'Citilin'],

  // ---- Urology, gynaecology, obstetrics ----
  ['Tamsulosin', '0.4 mg', 'Urimax 0.4', 'Contiflo OD', 'Veltam'],
  ['Tamsulosin + Dutasteride', '0.4/0.5 mg', 'Urimax-D', 'Veltam Plus', 'Dutalfa'],
  ['Silodosin', '8 mg', 'Silodal 8', 'Rapilif 8'],
  ['Alfuzosin', '10 mg', 'Alfoo 10', 'Alfusin 10'],
  ['Tolterodine', '2 mg', 'Roliten', 'Tolter'],
  ['Potassium citrate + Magnesium citrate', '1100/375 mg/5 ml', 'Urikind-K', 'Alkasol', 'Cital'],
  ['Flavoxate', '200 mg', 'Urispas', 'Flavospas'],
  ['Sildenafil', '50 mg', 'Penegra 50', 'Manforce 50', 'Suhagra 50'],
  ['Tadalafil', '10 mg', 'Megalis 10', 'Tadacip 10'],
  ['Progesterone (natural micronised)', '200 mg', 'Susten 200', 'Utrogestan 200', 'Gestofit'],
  ['Dydrogesterone', '10 mg', 'Duphaston', 'Dydroboon'],
  ['Norethisterone', '5 mg', 'Primolut-N', 'Regestrone'],
  ['Medroxyprogesterone', '10 mg', 'Meprate', 'Provera'],
  ['Clomiphene citrate', '50 mg', 'Fertyl', 'Siphene', 'Clofert'],
  ['Letrozole', '2.5 mg', 'Letroz', 'Femara', 'Letrozole'],
  ['Tranexamic acid', '500 mg', 'Pause 500', 'Trapic 500'],
  ['Tranexamic acid + Mefenamic acid', '500/250 mg', 'Trapic MF', 'Pause MF'],
  ['Combined oral contraceptive', '0.15/0.03 mg', 'Mala-D', 'Ovral-L', 'Novelon'],
  ['Drospirenone + Ethinyl estradiol', '3/0.03 mg', 'Yasmin', 'Crisanta', 'Tydroz'],
  ['Levonorgestrel emergency pill', '1.5 mg', 'i-pill', 'Unwanted 72'],
  ['Cabergoline', '0.5 mg', 'Cabgolin 0.5', 'Caberlin 0.5'],
  ['Myo-inositol + Folic acid sachet', '2 g', 'Fertisure-F', 'Ovafolic'],
  ['Doxylamine + Pyridoxine', '10/10 mg', 'Doxinate', 'Doxofol'],
  ['Isoxsuprine', '10 mg', 'Duvadilan', 'Isoxsuprine'],
  ['Nifedipine', '10 mg', 'Depin 10', 'Calcigard 10'],
  ['Calcium + Vitamin D3 + Folic acid (pregnancy)', '1 tab', 'Shelcal-M', 'Calcimax Forte'],
  ['Clotrimazole + Beclomethasone vaginal', '100 mg', 'Candid-B vaginal', 'Candiforce'],
  ['Clindamycin + Clotrimazole vaginal', '100/200 mg', 'Clingen', 'Candid CL'],
  ['Metronidazole vaginal gel', '0.75%', 'Metrogyl-V', 'Metrogel'],

  // ---- Dermatology ----
  ['Clobetasol propionate cream', '0.05%', 'Tenovate', 'Clobetamil', 'Dermovate'],
  ['Betamethasone valerate cream', '0.1%', 'Betnovate', 'Valbet'],
  ['Betamethasone + Neomycin cream', '0.1%/0.5%', 'Betnovate-N'],
  ['Mometasone cream', '0.1%', 'Momate', 'Elocon'],
  ['Fluticasone cream', '0.05%', 'Flutivate', 'Cutivate'],
  ['Hydrocortisone cream', '1%', 'Cortef', 'Wycort cream'],
  ['Clotrimazole + Beclomethasone cream', '1%/0.025%', 'Candid-B', 'Canesten-B'],
  ['Terbinafine cream', '1%', 'Sebifin', 'Terbicip cream'],
  ['Adapalene gel', '0.1%', 'Adaferin', 'Deriva'],
  ['Adapalene + Clindamycin gel', '0.1%/1%', 'Deriva-CMS', 'Adaferin-C'],
  ['Benzoyl peroxide gel', '2.5%', 'Persol', 'Benzonext'],
  ['Clindamycin gel', '1%', 'Clindac-A', 'Clinsol'],
  ['Azelaic acid cream', '20%', 'Aziderm', 'Acnederm'],
  ['Tretinoin cream', '0.025%', 'Retino-A', 'A-Ret'],
  ['Calamine lotion', '8%', 'Lacto Calamine', 'Caladryl'],
  ['Moisturising lotion (urea / lactic acid)', '10%', 'Venusia Max', 'Cetaphil', 'Moisturex'],
  ['Tacrolimus ointment', '0.1%', 'Tacroz Forte', 'Protopic'],
  ['Hydroquinone + Tretinoin + Mometasone cream', '2%/0.025%/0.1%', 'Melacare', 'Triluma'],
  ['Minoxidil solution', '5%', 'Mintop 5', 'Tugain 5'],
  ['Sunscreen', 'SPF 50', 'Suncros', 'La Shield', 'Photostable'],

  // ---- Eye, ear, mouth ----
  ['Moxifloxacin eye drops', '0.5%', 'Vigamox', 'Moxicip', 'Milflox'],
  ['Ciprofloxacin eye/ear drops', '0.3%', 'Ciplox', 'Cifran eye drops'],
  ['Tobramycin eye drops', '0.3%', 'Tobrex', 'Tobastar'],
  ['Tobramycin + Dexamethasone eye drops', '0.3%/0.1%', 'Tobradex', 'Tobaflam'],
  ['Carboxymethylcellulose eye drops', '0.5%', 'Refresh Tears', 'Lubistar', 'Tears Plus'],
  ['Olopatadine eye drops', '0.1%', 'Olopat', 'Pataday'],
  ['Ofloxacin ear drops', '0.3%', 'Otiflox', 'Oflox ear drops'],
  ['Clotrimazole + Beclomethasone + Lignocaine ear drops', '5 ml', 'Candibiotic', 'Otek-AC'],
  ['Wax dissolving ear drops', '10 ml', 'Waxsol', 'Cerumol'],
  ['Chlorhexidine mouthwash', '0.2%', 'Hexidine', 'Rexidin'],
  ['Choline salicylate + Lignocaine gel', '10 g', 'Dologel CT', 'Mucopain'],
  ['Triamcinolone oral paste', '0.1%', 'Kenacort oral paste'],
  ['Povidone-iodine gargle', '2%', 'Betadine gargle'],

  // ---- Injections commonly given in OPD ----
  ['Diclofenac injection', '75 mg/ml', 'Voveran injection', 'Dynapar AQ'],
  ['Pantoprazole injection', '40 mg', 'Pan IV', 'Pantocid IV'],
  ['Ondansetron injection', '2 mg/ml', 'Emeset injection', 'Zofer'],
  ['Dexamethasone injection', '4 mg/ml', 'Decadron', 'Dexona injection'],
  ['Pheniramine injection', '22.75 mg/ml', 'Avil injection'],
  ['Tetanus toxoid injection', '0.5 ml', 'TT vaccine', 'Tetavac'],
  ['Vitamin B12 injection', '1500 mcg', 'Trinerve', 'Methycobal injection'],
  ['Normal saline', '500 ml', 'NS 0.9%'],
  ['Ringer lactate', '500 ml', 'RL'],
  ['Dextrose normal saline', '500 ml', 'DNS'],
];

const LAB_TESTS: string[] = [
  // Haematology
  'CBC (Complete Blood Count)', 'Hemoglobin (Hb)', 'ESR', 'Peripheral smear', 'Platelet count', 'Reticulocyte count',
  'Blood group & Rh type', 'PT / INR', 'aPTT', 'D-Dimer', 'Bleeding time / Clotting time',
  // Diabetes
  'Blood Sugar (Fasting)', 'Blood Sugar (PP)', 'Blood Sugar (Random)', 'HbA1c', 'OGTT (75 g)', 'GCT (glucose challenge, 50 g)',
  'Fasting insulin', 'C-peptide', 'Urine microalbumin',
  // Kidney & liver
  'Kidney Function Test (KFT / RFT)', 'Serum creatinine', 'Blood urea / BUN', 'Serum uric acid', 'Serum electrolytes (Na, K, Cl)',
  'Serum calcium', 'Serum phosphorus', 'Serum magnesium', 'eGFR', 'Liver Function Test (LFT)', 'SGPT (ALT)', 'SGOT (AST)',
  'Serum bilirubin (total, direct)', 'Alkaline phosphatase', 'GGT', 'Serum albumin / total protein', 'Serum amylase', 'Serum lipase',
  // Lipids & cardiac
  'Lipid Profile', 'Total cholesterol', 'Triglycerides', 'Troponin I', 'Troponin T', 'CPK-MB', 'NT-proBNP', 'hs-CRP', 'Homocysteine',
  // Thyroid & hormones
  'Thyroid Profile (T3, T4, TSH)', 'TSH', 'Free T3 / Free T4', 'Anti-TPO antibodies', 'Prolactin', 'FSH', 'LH', 'Estradiol (E2)',
  'Progesterone', 'Testosterone (total)', 'AMH (Anti-Mullerian Hormone)', 'Cortisol (morning)', 'PTH', 'Beta-hCG (quantitative)',
  'Urine pregnancy test (UPT)', 'Semen analysis',
  // Vitamins & iron
  'Vitamin D (25-OH)', 'Vitamin B12', 'Folic acid (serum folate)', 'Serum iron / TIBC', 'Serum ferritin',
  // Infections & serology
  'CRP', 'Widal', 'Typhi dot (IgM)', 'Dengue NS1 antigen', 'Dengue IgM / IgG', 'Malaria antigen (rapid)', 'Malaria parasite smear',
  'Chikungunya IgM', 'Leptospira IgM', 'Scrub typhus IgM', 'HIV I & II', 'HBsAg', 'Anti-HCV', 'VDRL / RPR', 'Procalcitonin',
  'COVID-19 RT-PCR', 'COVID-19 rapid antigen', 'Influenza A/B rapid test', 'Mantoux test', 'Blood culture & sensitivity',
  'Sputum AFB', 'Sputum culture & sensitivity', 'CBNAAT / GeneXpert (TB)', 'H. pylori antigen (stool)', 'ASO titre',
  // Rheumatology & immunology
  'RA factor', 'Anti-CCP', 'ANA (IFA)', 'HLA-B27', 'IgE (total)', 'Allergy panel',
  // Urine & stool
  'Urine Routine & Microscopy', 'Urine culture & sensitivity', 'Urine albumin/creatinine ratio', '24-hour urine protein',
  'Stool Routine & Microscopy', 'Stool occult blood', 'Stool culture',
  // Tumour markers
  'PSA (total)', 'CA-125', 'CEA', 'AFP', 'CA 19-9',
  // Pregnancy & others
  'Double marker', 'Quadruple marker', 'NIPT', 'TORCH panel', 'Pap smear', 'HPV DNA test', 'Vaginal swab culture',
  'Throat swab culture', 'Pus culture & sensitivity', 'Body fluid analysis', 'FNAC', 'Biopsy / histopathology',
  // Panels
  'Fever panel', 'Anaemia profile', 'Arthritis profile', 'Diabetic profile', 'Full body health check-up', 'Pre-operative profile',
  'Antenatal profile', 'PCOS profile', 'Infertility profile (female)', 'Cardiac risk profile',
];

const RADIOLOGY: string[] = [
  // X-ray
  'Chest X-Ray PA view', 'Chest X-Ray AP view', 'X-Ray Abdomen (erect)', 'X-Ray KUB', 'X-Ray PNS (Waters view)',
  'X-Ray Cervical spine AP/Lateral', 'X-Ray Lumbosacral spine AP/Lateral', 'X-Ray Dorsal spine AP/Lateral', 'X-Ray Knee AP/Lateral',
  'X-Ray Both knees standing', 'X-Ray Shoulder AP', 'X-Ray Hip AP', 'X-Ray Pelvis AP', 'X-Ray Ankle AP/Lateral', 'X-Ray Foot AP/Oblique',
  'X-Ray Wrist AP/Lateral', 'X-Ray Hand AP/Oblique', 'X-Ray Elbow AP/Lateral', 'X-Ray Skull AP/Lateral', 'X-Ray Soft tissue neck',
  'X-Ray Mastoids', 'Dental OPG', 'Barium swallow', 'Barium meal follow-through', 'IVP', 'HSG (Hysterosalpingography)',
  // Ultrasound
  'USG Abdomen', 'USG Abdomen & Pelvis', 'USG Pelvis', 'USG KUB', 'USG Thyroid / Neck', 'USG Breast', 'USG Scrotum',
  'USG Soft tissue / local part', 'TVS (Transvaginal sonography)', 'Follicular monitoring', 'USG Obstetric (early pregnancy / dating)',
  'NT scan (11–14 weeks)', 'Anomaly scan (18–22 weeks)', 'Growth scan', 'Obstetric Doppler', 'Carotid Doppler',
  'Venous Doppler lower limb', 'Arterial Doppler lower limb', 'Renal Doppler', 'Liver elastography (FibroScan)', 'USG guided FNAC',
  // CT
  'CT Brain (plain)', 'CT Brain (contrast)', 'CT PNS', 'CT Chest (HRCT)', 'CT Abdomen & Pelvis (contrast)', 'CT KUB (plain)',
  'CT Cervical spine', 'CT Lumbar spine', 'CT Angiography', 'CT Coronary angiography', 'CT Temporal bone',
  // MRI
  'MRI Brain', 'MRI Brain with MRA', 'MRI Cervical spine', 'MRI Dorsal spine', 'MRI Lumbosacral spine', 'MRI Knee', 'MRI Shoulder',
  'MRI Hip', 'MRI Ankle', 'MRI Pelvis', 'MRI Abdomen', 'MRCP', 'MRI Breast',
  // Cardiac & others
  'ECG', '2D Echo', 'TMT (Treadmill test)', 'Holter monitoring (24 h)', 'ABPM (24 h BP)', 'Mammography', 'DEXA scan (bone density)',
  'PFT (Pulmonary function test)', 'Spirometry', 'EEG', 'NCV / EMG', 'Audiometry (PTA)', 'Upper GI endoscopy', 'Colonoscopy',
  'PET-CT',
];

export const STARTER_CATALOG: StarterItem[] = [
  ...MEDICINES.map(([name, strength, ...brands]) => ({ kind: 'MEDICINE' as const, name, strength, brands })),
  ...LAB_TESTS.map((name) => ({ kind: 'LAB_TEST' as const, name })),
  ...RADIOLOGY.map((name) => ({ kind: 'RADIOLOGY' as const, name })),
];
