// Standard medicine lists for Ayurvedic and Homeopathic clinics, in the
// same shape as the allopathic list in starterCatalog.ts: [medicine,
// strength / pack, makers' products...]. Loaded by "Load standard list"
// (and at registration) according to the clinic's system of medicine;
// every entry can be edited or deleted afterwards.
//
// Makers' names are examples of widely sold products for reference, not
// an endorsement or an exhaustive market list.

type Med = [string, string, ...string[]];

export const AYURVEDIC: Med[] = [
  // ---- Churna (powders) ----
  ['Triphala Churna', '100 g', 'Dabur Triphala Churna', 'Baidyanath Triphala Churna', 'Patanjali Divya Triphala Churna'],
  ['Ashwagandha Churna', '100 g', 'Dabur Ashwagandha Churna', 'Baidyanath Ashwagandha Churna', 'Patanjali Divya Ashwagandha Churna'],
  ['Avipattikar Churna', '100 g', 'Baidyanath Avipattikar Churna', 'Dabur Avipattikar Churna', 'Patanjali Divya Avipattikar Churna'],
  ['Sitopaladi Churna', '50 g', 'Dabur Sitopaladi Churna', 'Baidyanath Sitopaladi Churna', 'Patanjali Divya Sitopaladi Churna'],
  ['Talisadi Churna', '50 g', 'Baidyanath Talisadi Churna', 'Dabur Talisadi Churna'],
  ['Hingvashtak Churna', '60 g', 'Dabur Hingvashtak Churna', 'Baidyanath Hingwashtak Churna'],
  ['Panchasakar Churna', '100 g', 'Baidyanath Panchasakar Churna'],
  ['Isabgol (Psyllium husk)', '100 g', 'Sat Isabgol', 'Dabur Isabgol'],
  ['Yashtimadhu (Mulethi) Churna', '100 g', 'Baidyanath Yashtimadhu Churna', 'Patanjali Divya Mulethi Churna'],
  ['Shatavari Churna', '100 g', 'Baidyanath Shatavari Churna', 'Patanjali Divya Shatavari Churna'],
  ['Trikatu Churna', '50 g', 'Baidyanath Trikatu Churna'],
  ['Lavan Bhaskar Churna', '60 g', 'Baidyanath Lavan Bhaskar Churna', 'Dabur Lavan Bhaskar Churna'],
  // ---- Vati / Gutika (tablets) ----
  ['Arogyavardhini Vati', '40 tab', 'Baidyanath Arogyavardhini Bati', 'Dabur Arogyavardhini Vati', 'Patanjali Divya Arogyavardhini Vati'],
  ['Chandraprabha Vati', '40 tab', 'Baidyanath Chandraprabha Vati', 'Dabur Chandraprabha Vati', 'Patanjali Divya Chandraprabha Vati'],
  ['Sanjeevani Vati', '40 tab', 'Baidyanath Sanjivani Vati', 'Dabur Sanjivani Vati'],
  ['Chitrakadi Vati', '40 tab', 'Baidyanath Chitrakadi Vati', 'Dabur Chitrakadi Bati'],
  ['Giloy Ghan Vati', '60 tab', 'Patanjali Divya Giloy Ghanvati', 'Dabur Giloy Ghanvati', 'Himalaya Guduchi'],
  ['Mahasudarshan Ghan Vati', '40 tab', 'Patanjali Divya Mahasudarshan Ghanvati'],
  ['Kanchnar Guggulu', '40 tab', 'Baidyanath Kanchnar Guggulu', 'Dabur Kanchnar Guggulu', 'Patanjali Divya Kanchnar Guggul'],
  ['Kaishore Guggulu', '40 tab', 'Baidyanath Kaishore Guggulu', 'Dabur Kaishore Guggulu', 'Patanjali Divya Kaishore Guggul'],
  ['Yograj Guggulu', '40 tab', 'Baidyanath Yograj Guggulu', 'Dabur Yogaraj Guggulu', 'Patanjali Divya Yograj Guggul'],
  ['Mahayograj Guggulu', '40 tab', 'Baidyanath Mahayograj Guggulu', 'Dabur Mahayograj Guggulu'],
  ['Triphala Guggulu', '40 tab', 'Baidyanath Triphala Guggulu', 'Dabur Triphala Guggulu', 'Patanjali Divya Triphala Guggul'],
  ['Gokshuradi Guggulu', '40 tab', 'Baidyanath Gokshuradi Guggulu', 'Dabur Gokshuradi Guggulu'],
  ['Punarnavadi Mandur', '40 tab', 'Baidyanath Punarnavadi Mandur', 'Dabur Punarnavadi Mandur'],
  ['Medohar Guggulu', '40 tab', 'Baidyanath Medohar Guggulu', 'Patanjali Divya Medohar Vati'],
  ['Shankha Vati', '40 tab', 'Baidyanath Shankh Vati', 'Dabur Shankha Vati'],
  ['Lasunadi Vati', '40 tab', 'Baidyanath Lasunadi Vati'],
  ['Kutajghan Vati', '40 tab', 'Baidyanath Kutajghan Vati', 'Dabur Kutajghan Vati'],
  ['Brahmi Vati', '40 tab', 'Baidyanath Brahmi Vati', 'Patanjali Divya Medha Vati'],
  ['Khadiradi Vati', '40 tab', 'Baidyanath Khadiradi Vati', 'Dabur Khadiradi Gutika'],
  ['Shilajit', '30 cap', 'Dabur Shilajit Gold', 'Baidyanath Shilajit', 'Patanjali Divya Shilajit Capsule'],
  // ---- Asava / Arishta (fermented liquids) ----
  ['Dashmoolarishta', '450 ml', 'Dabur Dashmularishta', 'Baidyanath Dashmularishta', 'Patanjali Divya Dashmularishta'],
  ['Arjunarishta', '450 ml', 'Baidyanath Arjunarishta', 'Dabur Arjunarishta'],
  ['Ashokarishta', '450 ml', 'Dabur Ashokarishta', 'Baidyanath Ashokarishta', 'Patanjali Divya Ashokarishta'],
  ['Kumaryasava', '450 ml', 'Baidyanath Kumaryasava', 'Dabur Kumaryasava'],
  ['Abhayarishta', '450 ml', 'Baidyanath Abhayarishta', 'Dabur Abhayarishta'],
  ['Drakshasava', '450 ml', 'Dabur Drakshasava', 'Baidyanath Drakshasava'],
  ['Saraswatarishta', '450 ml', 'Baidyanath Saraswatarishta', 'Dabur Saraswatarishta'],
  ['Lohasava', '450 ml', 'Baidyanath Lohasava', 'Dabur Lohasava'],
  ['Punarnavasava', '450 ml', 'Baidyanath Punarnavasava', 'Dabur Punarnavasava'],
  ['Kanakasava', '450 ml', 'Baidyanath Kanakasava', 'Kottakkal Kanakasavam'],
  ['Amritarishta', '450 ml', 'Baidyanath Amritarishta', 'Kottakkal Amrutharishtam'],
  ['Balarishta', '450 ml', 'Baidyanath Balarishta', 'Kottakkal Balarishtam'],
  // ---- Avaleha / Paka (jams) ----
  ['Chyawanprash', '500 g', 'Dabur Chyawanprash', 'Baidyanath Chyawanprash', 'Patanjali Chyawanprash', 'Zandu Chyawanprash'],
  ['Agastya Haritaki Avaleha', '250 g', 'Baidyanath Agastya Haritaki', 'Kottakkal Agastya Rasayanam'],
  ['Kushmanda Avaleha', '250 g', 'Baidyanath Kushmanda Avaleha'],
  ['Vasavaleha', '250 g', 'Baidyanath Vasavaleha', 'Dabur Vasavaleha'],
  // ---- Bhasma / Rasa ----
  ['Praval Pishti', '10 g', 'Baidyanath Praval Pishti', 'Dabur Praval Pishti'],
  ['Mukta Pishti', '5 g', 'Baidyanath Mukta Pishti'],
  ['Godanti Bhasma', '10 g', 'Baidyanath Godanti Bhasma', 'Dabur Godanti Bhasma'],
  ['Shankh Bhasma', '10 g', 'Baidyanath Shankh Bhasma', 'Dabur Shankh Bhasma'],
  ['Tamra Bhasma', '5 g', 'Baidyanath Tamra Bhasma'],
  ['Swarna Makshik Bhasma', '5 g', 'Baidyanath Swarna Makshik Bhasma', 'Dabur Swarna Makshik Bhasma'],
  ['Sootshekhar Ras', '40 tab', 'Baidyanath Sootshekhar Ras', 'Dabur Sootshekhar Ras'],
  ['Laxmivilas Ras', '40 tab', 'Baidyanath Laxmi Vilas Ras', 'Dabur Laxmi Vilas Ras'],
  ['Kamdudha Ras', '40 tab', 'Baidyanath Kamdudha Ras', 'Dabur Kamdudha Ras'],
  ['Mahavat Vidhwansan Ras', '40 tab', 'Baidyanath Mahavatvidhwansan Ras'],
  ['Tribhuvan Kirti Ras', '40 tab', 'Baidyanath Tribhuvan Kirti Ras', 'Dabur Tribhuvan Kirti Ras'],
  // ---- Kashaya / Kwath ----
  ['Maharasnadi Kwath', '450 ml', 'Baidyanath Maharasnadi Kwath', 'Kottakkal Maharasnadi Kashayam'],
  ['Punarnavadi Kashayam', '200 ml', 'Kottakkal Punarnavadi Kashayam', 'Arya Vaidya Pharmacy Punarnavadi Kashayam'],
  ['Guluchyadi Kashayam', '200 ml', 'Kottakkal Guluchyadi Kashayam'],
  ['Varanadi Kashayam', '200 ml', 'Kottakkal Varanadi Kashayam'],
  ['Dhanwantharam Kashayam', '200 ml', 'Kottakkal Dhanwantharam Kashayam'],
  // ---- Taila / Ghrita ----
  ['Mahanarayan Taila', '100 ml', 'Dabur Mahanarayan Tail', 'Baidyanath Mahanarayan Tel', 'Patanjali Divya Peedantak Tail'],
  ['Ksheerabala Taila', '200 ml', 'Kottakkal Ksheerabala Thailam', 'Arya Vaidya Pharmacy Ksheerabala Thailam'],
  ['Dhanwantharam Taila', '200 ml', 'Kottakkal Dhanwantharam Thailam'],
  ['Anu Taila (nasal drops)', '10 ml', 'Baidyanath Anu Tel', 'Patanjali Divya Anu Tail'],
  ['Brahmi Ghrita', '150 g', 'Baidyanath Brahmi Ghrit', 'Kottakkal Brahmi Ghritham'],
  ['Triphala Ghrita', '150 g', 'Baidyanath Triphala Ghrit', 'Kottakkal Triphala Ghritham'],
  ['Phala Ghrita', '150 g', 'Baidyanath Phal Ghrit', 'Kottakkal Phala Sarpis'],
  // ---- Proprietary Ayurvedic ----
  ['Liv.52', 'tablet', 'Himalaya Liv.52', 'Himalaya Liv.52 DS'],
  ['Liv.52 syrup', '200 ml', 'Himalaya Liv.52 Syrup'],
  ['Septilin', 'tablet', 'Himalaya Septilin'],
  ['Cystone', 'tablet', 'Himalaya Cystone'],
  ['Gasex', 'tablet', 'Himalaya Gasex'],
  ['Pilex', 'tablet', 'Himalaya Pilex'],
  ['Pilex ointment', '30 g', 'Himalaya Pilex Ointment'],
  ['Rumalaya Forte', 'tablet', 'Himalaya Rumalaya Forte'],
  ['Rumalaya gel', '30 g', 'Himalaya Rumalaya Gel'],
  ['Koflet syrup', '100 ml', 'Himalaya Koflet'],
  ['Mentat', 'tablet', 'Himalaya Mentat'],
  ['Evecare syrup', '200 ml', 'Himalaya Evecare'],
  ['Confido', 'tablet', 'Himalaya Confido'],
  ['Tentex Forte', 'tablet', 'Himalaya Tentex Forte'],
  ['Neeri', 'tablet', 'AIMIL Neeri'],
  ['Neeri KFT', 'syrup 200 ml', 'AIMIL Neeri KFT'],
  ['BGR-34', 'tablet', 'AIMIL BGR-34'],
  ['Diabecon', 'tablet', 'Himalaya Diabecon'],
  ['Madhunashini Vati', '60 tab', 'Patanjali Divya Madhunashini Vati'],
  ['Mukta Vati', '60 tab', 'Patanjali Divya Mukta Vati'],
  ['Kayakalp Vati', '60 tab', 'Patanjali Divya Kayakalp Vati'],
  ['Swasari Pravahi', '100 ml', 'Patanjali Divya Swasari Pravahi', 'Patanjali Divya Swasari Ras'],
  ['Honitus syrup', '100 ml', 'Dabur Honitus'],
  ['Pudin Hara', 'pearls / liquid', 'Dabur Pudin Hara'],
  ['Zandu Balm', '8 ml', 'Zandu Balm'],
  ['Pancharishta', '450 ml', 'Zandu Pancharishta'],
  ['Kofol syrup', '100 ml', 'Charak Kofol'],
  ['M2-Tone', 'tablet / syrup', 'Charak M2-Tone'],
  ['Arshoghni Vati', '40 tab', 'Patanjali Divya Arshkalp Vati', 'Baidyanath Arshoghni Vati'],
  ['Gokshura', 'capsule', 'Himalaya Gokshura'],
  ['Ashwagandha', 'capsule / tablet', 'Himalaya Ashwagandha', 'Organic India Ashwagandha'],
  ['Tulsi', 'drops / capsule', 'Himalaya Tulasi', 'Organic India Tulsi', 'Patanjali Divya Tulsi Ghanvati'],
  ['Neem', 'capsule / tablet', 'Himalaya Neem', 'Patanjali Divya Neem Ghanvati'],
  ['Guduchi', 'capsule / tablet', 'Himalaya Guduchi', 'Organic India Giloy'],
  ['Arjuna', 'capsule / tablet', 'Himalaya Arjuna', 'Organic India Arjuna'],
  ['Shallaki (Boswellia)', 'capsule / tablet', 'Himalaya Shallaki', 'Organic India Boswellia'],
  ['Brahmi', 'capsule / tablet', 'Himalaya Brahmi', 'Organic India Brahmi'],
  ['Kumkumadi Taila', '10 ml', 'Kottakkal Kumkumadi Thailam', 'Kama Ayurveda Kumkumadi'],
  ['Jatyadi Taila', '100 ml', 'Baidyanath Jatyadi Tel', 'Kottakkal Jathyadi Thailam'],
];

export const HOMEOPATHIC: Med[] = [
  // ---- Dilutions (potencies) ----
  ...(
    [
      'Aconitum Napellus', 'Arnica Montana', 'Arsenicum Album', 'Belladonna', 'Bryonia Alba', 'Calcarea Carbonica',
      'Calcarea Phosphorica', 'Carbo Vegetabilis', 'Chamomilla', 'Cina', 'Colocynthis', 'Dulcamara', 'Gelsemium Sempervirens',
      'Hepar Sulphuris', 'Hypericum Perfoliatum', 'Ignatia Amara', 'Ipecacuanha', 'Kali Bichromicum', 'Lachesis', 'Ledum Palustre',
      'Lycopodium Clavatum', 'Mercurius Solubilis', 'Natrum Muriaticum', 'Nux Vomica', 'Phosphorus', 'Podophyllum', 'Pulsatilla',
      'Rhus Toxicodendron', 'Ruta Graveolens', 'Sepia', 'Silicea', 'Spongia Tosta', 'Sulphur', 'Thuja Occidentalis',
      'Allium Cepa', 'Antimonium Tartaricum', 'Apis Mellifica', 'Causticum', 'Drosera', 'Euphrasia', 'Ferrum Phosphoricum',
      'Graphites', 'Kali Carbonicum', 'Magnesia Phosphorica', 'Natrum Sulphuricum', 'Staphysagria', 'Symphytum', 'Veratrum Album',
    ] as const
  ).flatMap((remedy): Med[] => ['30C', '200C', '1M'].map((p): Med => [remedy, p, 'SBL', 'Dr. Reckeweg', 'Schwabe', 'Bakson'])),
  // ---- Mother tinctures ----
  ...(
    [
      'Berberis Vulgaris', 'Calendula Officinalis', 'Crataegus Oxyacantha', 'Echinacea Angustifolia', 'Justicia Adhatoda',
      'Ocimum Sanctum', 'Rauwolfia Serpentina', 'Syzygium Jambolanum', 'Avena Sativa', 'Alfalfa', 'Carduus Marianus',
      'Chelidonium Majus', 'Passiflora Incarnata', 'Thuja Occidentalis', 'Arnica Montana', 'Cantharis', 'Terminalia Arjuna',
      'Tribulus Terrestris', 'Blatta Orientalis', 'Hydrastis Canadensis',
    ] as const
  ).map((remedy): Med => [`${remedy} Q (mother tincture)`, '30 ml', 'SBL', 'Dr. Reckeweg', 'Schwabe', 'Bakson']),
  // ---- Biochemic (tissue salts) ----
  ...(
    [
      'Calcarea Fluorica', 'Calcarea Phosphorica', 'Calcarea Sulphurica', 'Ferrum Phosphoricum', 'Kali Muriaticum',
      'Kali Phosphoricum', 'Kali Sulphuricum', 'Magnesia Phosphorica', 'Natrum Muriaticum', 'Natrum Phosphoricum',
      'Natrum Sulphuricum', 'Silicea',
    ] as const
  ).map((salt): Med => [`${salt} (biochemic)`, '6X, 25 g', 'SBL', 'Dr. Reckeweg', 'Schwabe', 'Bakson']),
  ['Bio-Combination 1 (anaemia)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 4 (constipation)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 5 (cough, cold)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 6 (colds)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 7 (diabetes)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 9 (diarrhoea)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 10 (dysmenorrhoea)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 12 (fever)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 15 (headache)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 17 (piles)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 20 (skin)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 21 (teething)', '25 g', 'SBL', 'Bakson'],
  ['Bio-Combination 25 (indigestion)', '25 g', 'SBL', 'Bakson'],
  ['Five Phos', '6X, 20 g', 'SBL', 'Dr. Reckeweg', 'Schwabe'],
  // ---- Patent / combination remedies ----
  ['Dr. Reckeweg R1 (inflammation)', '22 ml', 'Dr. Reckeweg'],
  ['Dr. Reckeweg R5 (gastritis)', '22 ml', 'Dr. Reckeweg'],
  ['Dr. Reckeweg R6 (influenza, fever)', '22 ml', 'Dr. Reckeweg'],
  ['Dr. Reckeweg R7 (liver)', '22 ml', 'Dr. Reckeweg'],
  ['Dr. Reckeweg R8 (cough)', '22 ml', 'Dr. Reckeweg'],
  ['Dr. Reckeweg R11 (rheumatism)', '22 ml', 'Dr. Reckeweg'],
  ['Dr. Reckeweg R40 (diabetes)', '22 ml', 'Dr. Reckeweg'],
  ['Dr. Reckeweg R89 (hair)', '22 ml', 'Dr. Reckeweg'],
  ['SBL Drops No. 7 (asthma)', '30 ml', 'SBL'],
  ['SBL Drops No. 20 (cold)', '30 ml', 'SBL'],
  ['Bakson Sinus Aid', 'tablet', 'Bakson'],
  ['Bakson Tonsil Aid', 'tablet', 'Bakson'],
  ['Alfalfa Tonic', '200 ml', 'SBL', 'Bakson', 'Schwabe'],
  ['Five Phos syrup', '200 ml', 'SBL'],
  ['Calendula ointment', '25 g', 'SBL', 'Schwabe', 'Dr. Reckeweg'],
  ['Arnica ointment', '25 g', 'SBL', 'Schwabe', 'Dr. Reckeweg'],
  ['Arnica hair oil', '100 ml', 'SBL', 'Bakson'],
  ['Cough syrup (homeopathic)', '100 ml', 'SBL Bronchoril', 'Schwabe Alpha Cough', 'Bakson Coldcure'],
  ['Stye drops / eye drops (Euphrasia)', '10 ml', 'SBL Euphrasia Eye Drops', 'Schwabe Euphrasia Eye Drops'],
  ['Globules (sac lac, blank pills)', '#30, 450 g', 'SBL', 'Bakson'],
];
